# Generated by Django 4.2 on 2023-06-26 18:06

import ckeditor.fields
import common.upload_to_files
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=common.upload_to_files.cooperation_files, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Сотрудничество',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
        migrations.CreateModel(
            name='EduProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учебный процесс',
                'verbose_name_plural': 'Учебные процессы',
            },
        ),
        migrations.CreateModel(
            name='InternationalCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=230, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.international_main_img, verbose_name='Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to=common.upload_to_files.international_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Договор (PDF)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Международное сотрудничество',
                'verbose_name_plural': 'Международные сотрудничество',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InternationalCooperationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.international_images, verbose_name='Фотография')),
                ('international', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.internationalcooperation')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='EduProcessFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=common.upload_to_files.edu_process_files, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], verbose_name='Файл')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.eduprocess', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл учебного процесса',
                'verbose_name_plural': 'Файлы учебных процессов',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=common.upload_to_files.document_files, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'webp'])], verbose_name='Файл')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документа',
            },
        ),
    ]
