# Generated by Django 4.2 on 2026-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receptionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionpage',
            name='heading_italic',
        ),
        migrations.RemoveField(
            model_name='receptionpage',
            name='heading_italic_en',
        ),
        migrations.RemoveField(
            model_name='receptionpage',
            name='heading_italic_ky',
        ),
        migrations.RemoveField(
            model_name='receptionpage',
            name='heading_italic_ru',
        ),
        migrations.AlterField(
            model_name='receptionpage',
            name='heading',
            field=models.CharField(default='Дорогие <i>абитуриенты!</i>', help_text='Можно вставить HTML — например, оберни слово в &lt;i&gt;...&lt;/i&gt; чтобы выделить курсивом.', max_length=240, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='receptionpage',
            name='heading_en',
            field=models.CharField(default='Дорогие <i>абитуриенты!</i>', help_text='Можно вставить HTML — например, оберни слово в &lt;i&gt;...&lt;/i&gt; чтобы выделить курсивом.', max_length=240, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='receptionpage',
            name='heading_ky',
            field=models.CharField(default='Дорогие <i>абитуриенты!</i>', help_text='Можно вставить HTML — например, оберни слово в &lt;i&gt;...&lt;/i&gt; чтобы выделить курсивом.', max_length=240, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='receptionpage',
            name='heading_ru',
            field=models.CharField(default='Дорогие <i>абитуриенты!</i>', help_text='Можно вставить HTML — например, оберни слово в &lt;i&gt;...&lt;/i&gt; чтобы выделить курсивом.', max_length=240, null=True, verbose_name='Заголовок'),
        ),
    ]
