# Generated by Django 4.2 on 2026-07-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_receptionpage_heading_italic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='+996 (555) 10-68-86', max_length=40, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, default='+996 (555) 10-68-86', max_length=40, verbose_name='WhatsApp (номер)')),
                ('email', models.EmailField(blank=True, default='info@kiuc.kg', max_length=254, verbose_name='Email')),
                ('address_short', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается в футере.', max_length=200, verbose_name='Адрес (кратко)')),
                ('address_short_ru', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается в футере.', max_length=200, null=True, verbose_name='Адрес (кратко)')),
                ('address_short_en', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается в футере.', max_length=200, null=True, verbose_name='Адрес (кратко)')),
                ('address_short_ky', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается в футере.', max_length=200, null=True, verbose_name='Адрес (кратко)')),
                ('address_full', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается на странице «Контакты».', max_length=255, verbose_name='Адрес (полностью)')),
                ('address_full_ru', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается на странице «Контакты».', max_length=255, null=True, verbose_name='Адрес (полностью)')),
                ('address_full_en', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается на странице «Контакты».', max_length=255, null=True, verbose_name='Адрес (полностью)')),
                ('address_full_ky', models.CharField(blank=True, default='Чуйская обл., Сокулукский р., Шопоков, ул. Машиностроительная, 25а', help_text='Показывается на странице «Контакты».', max_length=255, null=True, verbose_name='Адрес (полностью)')),
                ('address_url', models.URLField(blank=True, default='https://go.2gis.com/heri6', help_text='Куда ведёт адрес в футере — например, ссылка 2ГИС.', verbose_name='Ссылка на карту')),
                ('map_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1056.5517421664722!2d74.33675432651926!3d42.86404867698774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x389ed965acdeec3b%3A0xa3d3a2bafb4618e1!2z0JrRi9GA0LPRi9C30YHQutC40Lkg0JzQtdC20LTRg9C90LDRgNC-0LTQvdGL0Lkg0KPQvdC40LLQtdGA0YHQsNC70YzQvdGL0Lkg0JrQvtC70LvQtdC00LYgKNCa0JzQo9CaKQ!5e1!3m2!1sru!2skg!4v1682148536639!5m2!1sru!2skg', help_text='Адрес из атрибута src кода Google Maps → «Поделиться» → «Встраивание карт».', max_length=1000, verbose_name='Встроенная карта')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/kilc_university/', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/kiuckg', verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, default='https://www.youtube.com/@KIUCUniversity', verbose_name='YouTube')),
                ('college_label', models.CharField(blank=True, default='college.kiuc.kg', max_length=120, verbose_name='Подпись сайта колледжа')),
                ('college_url', models.URLField(blank=True, default='https://college.kiuc.kg/', verbose_name='Сайт колледжа')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакты института',
                'verbose_name_plural': 'Контакты института',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=100, verbose_name='Порядковый номер')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=150, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=150, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=150, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('position_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp (номер)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('contact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.sitecontact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Менеджер приёмной комиссии',
                'verbose_name_plural': 'Менеджеры приёмной комиссии',
                'ordering': ('number', 'id'),
            },
        ),
    ]
