# Generated by Django 4.2 on 2023-10-25 09:38

import common.upload_to_files
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcouncil',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=common.upload_to_files.student_file, verbose_name='Фото студента'),
        ),
    ]
